install:
	corepack pnpm install

build:
	corepack pnpm build

dev:
	corepack pnpm dev

test:
	corepack pnpm test

test-e2e:
	corepack pnpm test:e2e

lint:
	corepack pnpm lint

format:
	corepack pnpm format:write
